version: 2
jobs:
  staging:
    docker:
      - image: circleci/node:10.7
    steps:
      - checkout
      - run:
          name: npm install
          command: npm i
      - run:
          name: Deploy to Firebase Hosting (Staging)
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project iosdc-cfps19-staging

workflows:
  version: 2
  staging:
    jobs:
      - staging:
          filters:
            branches:
              only: welcome-cicd
